export default {
  BOOK: 'book_screen',
  COURSE: 'course_screen',
  GAME: 'game_screen',
  HOME: 'home_screen',
  LESSON: 'lesson_screen',
  LOGIN: 'login_screen',
  MAIN: 'main_screen',
  PROFILE: 'profile_screen',
  SIGNUP: 'signup_screen',
  RESOURCE: 'resource_screen',
  SCHEDULE: 'schedule_screen',
  WELCOME: 'welcome_screen',
  SPLASH: 'splash_screen',
}